// <auto-generated />
using System;
using Khedmetak.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Khedmetak.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705181924_AddFeeTiersAndImportantNotes")]
    partial class AddFeeTiersAndImportantNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Khedmetak.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "الأحوال المدنية"
                        },
                        new
                        {
                            Id = 2,
                            Name = "المرور"
                        },
                        new
                        {
                            Id = 3,
                            Name = "التعليم"
                        },
                        new
                        {
                            Id = 4,
                            Name = "الصحة"
                        },
                        new
                        {
                            Id = 5,
                            Name = "التموين"
                        });
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GovServiceId")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GovServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.GovService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("EstimatedFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("NeedsGuarantee")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderEntity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SrvDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SrvFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SrvName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SrvTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("GovServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DeliveryMethod = "",
                            EstimatedFees = 50m,
                            NeedsGuarantee = false,
                            ProviderEntity = "",
                            SrvDesc = "إصدار بطاقة رقم قومي لأول مرة",
                            SrvFees = 50m,
                            SrvName = "استخراج بطاقة رقم قومي",
                            SrvTime = "7 أيام",
                            TargetAudience = ""
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DeliveryMethod = "",
                            EstimatedFees = 50m,
                            NeedsGuarantee = false,
                            ProviderEntity = "",
                            SrvDesc = "تجديد بطاقة الرقم القومي المنتهية",
                            SrvFees = 50m,
                            SrvName = "تجديد بطاقة رقم قومي",
                            SrvTime = "3 أيام",
                            TargetAudience = ""
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            DeliveryMethod = "",
                            EstimatedFees = 500m,
                            NeedsGuarantee = false,
                            ProviderEntity = "",
                            SrvDesc = "تجديد رخصة المركبة",
                            SrvFees = 500m,
                            SrvName = "تجديد رخصة سيارة",
                            SrvTime = "يوم واحد",
                            TargetAudience = ""
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DeliveryMethod = "",
                            EstimatedFees = 30m,
                            NeedsGuarantee = false,
                            ProviderEntity = "",
                            SrvDesc = "إصدار شهادة ميلاد بدل فاقد",
                            SrvFees = 30m,
                            SrvName = "استخراج بدل فاقد شهادة ميلاد",
                            SrvTime = "فوري",
                            TargetAudience = ""
                        });
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.Khedmetak.DAL.Entities.CitizenProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FloorNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsVerifiedViaDigitalPortal")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CitizenProfiles");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FawryRefNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantRefNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.RequiredDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<int>("GovServiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GovServiceId");

                    b.ToTable("RequiredDocuments");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceFeeTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GovServiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRefundable")
                        .HasColumnType("bit");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GovServiceId");

                    b.ToTable("ServiceFeeTiers");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceGeneralDocs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GovServiceId");

                    b.ToTable("ServiceGeneralDocs");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceImportantNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("GovServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("GovServiceId");

                    b.ToTable("ServiceImportantNotes");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GovServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovServiceId");

                    b.ToTable("ServiceOptions");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceOptionChoices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Choice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceOptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOptionId");

                    b.ToTable("ServiceOptionChoices");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceSteps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GovServiceId")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovServiceId");

                    b.ToTable("ServiceSteps");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e7492cfa-e160-49b8-a6d1-817abcf992bf",
                            CreatedAt = new DateTime(2026, 7, 5, 18, 19, 20, 865, DateTimeKind.Utc).AddTicks(7761),
                            Email = "fathi@khedmetak.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Fathi",
                            NormalizedEmail = "FATHI@KHEDMETAK.COM",
                            NormalizedUserName = "FATHI",
                            Password = "12345678",
                            PasswordHash = "AQAAAAIAAYagAAAAELWysayBUhLrcIwTUzDgKPY3AorJZwTFLQBooRkyyrhtB4RLjfH6ThQo5ycg17nm3w==",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "f4fb76b8-2ea9-42b7-876a-39fbcf9e6cf4",
                            TwoFactorEnabled = false,
                            UserName = "Fathi"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df768913-9118-4a9f-a496-e26bbbc23eef",
                            CreatedAt = new DateTime(2026, 7, 5, 18, 19, 21, 31, DateTimeKind.Utc).AddTicks(7915),
                            Email = "aya@khedmetak.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Aya",
                            NormalizedEmail = "AYA@KHEDMETAK.COM",
                            NormalizedUserName = "AYA",
                            Password = "12345678",
                            PasswordHash = "AQAAAAIAAYagAAAAEFpPg+xkY/aOKUYPVQkw3Ex1j6csejEkDg1xzduIcy+GgiXrK0tLYIiefYmL6791Zw==",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "bc521d96-c167-4277-a859-00ef1295beea",
                            TwoFactorEnabled = false,
                            UserName = "Aya"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b1f5fe6b-67a4-44b7-bdc6-2c93d9fb34d0",
                            CreatedAt = new DateTime(2026, 7, 5, 18, 19, 21, 197, DateTimeKind.Utc).AddTicks(2618),
                            Email = "naglaa@khedmetak.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Naglaa",
                            NormalizedEmail = "NAGLAA@KHEDMETAK.COM",
                            NormalizedUserName = "NAGLAA",
                            Password = "12345678",
                            PasswordHash = "AQAAAAIAAYagAAAAEMsj4ei2696yneKErHse5KLU4TLGAhFiCVmG+QH9KVhHCUM3Sn1akqgeY+jSNybYQg==",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "cbe62da6-dbdb-4fbc-bdf8-18e388ffc811",
                            TwoFactorEnabled = false,
                            UserName = "Naglaa"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5c5fbef1-cb69-42b7-99e2-348f6cfef7e9",
                            CreatedAt = new DateTime(2026, 7, 5, 18, 19, 21, 365, DateTimeKind.Utc).AddTicks(8804),
                            Email = "rahma@khedmetak.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Rahma",
                            NormalizedEmail = "RAHMA@KHEDMETAK.COM",
                            NormalizedUserName = "RAHMA",
                            Password = "12345678",
                            PasswordHash = "AQAAAAIAAYagAAAAEL2icm+3DLiq/5qF6EGina/+J8ShoEma+kSlzmUFxxNqs7S3IossIO0tPpb9otVN4A==",
                            PhoneNumberConfirmed = false,
                            Role = "User",
                            SecurityStamp = "d7d91e6b-e53b-4861-a53d-82c5f1fa6d03",
                            TwoFactorEnabled = false,
                            UserName = "Rahma"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f1e2d3c4-7777-8888-9999-aaaabbbbcccc",
                            CreatedAt = new DateTime(2026, 7, 5, 18, 19, 21, 531, DateTimeKind.Utc).AddTicks(6968),
                            Email = "admin@khedmetak.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@KHEDMETAK.COM",
                            NormalizedUserName = "ADMIN",
                            Password = "Admin@123",
                            PasswordHash = "AQAAAAIAAYagAAAAEGO1kZmIIdzFqrvv9cSM6+msD3RnpWYUei2PHs3wOIuK6BGoYGjVL4KZos0nF2vUgQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "a1b2c3d4-1111-2222-3333-444455556666",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.UserDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChatSessionId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequiredDocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("RequiredDocumentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDocuments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ChatMessage", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.ChatSession", "ChatSession")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ChatSession", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.Category", "Category")
                        .WithMany("ChatSessions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Khedmetak.DAL.Entities.GovService", "GovService")
                        .WithMany()
                        .HasForeignKey("GovServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Khedmetak.DAL.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("GovService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.Feedback", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.ChatSession", "ChatSession")
                        .WithOne("Feedback")
                        .HasForeignKey("Khedmetak.DAL.Entities.Feedback", "ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Khedmetak.DAL.Entities.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.GovService", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.Category", "Category")
                        .WithMany("GovServices")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.Khedmetak.DAL.Entities.CitizenProfile", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.User", "User")
                        .WithOne("CitizenProfile")
                        .HasForeignKey("Khedmetak.DAL.Entities.Khedmetak.DAL.Entities.CitizenProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.Payment", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.RequiredDocument", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.GovService", "GovService")
                        .WithMany("RequiredDocuments")
                        .HasForeignKey("GovServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GovService");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceFeeTier", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.GovService", "GovService")
                        .WithMany("ServiceFeeTiers")
                        .HasForeignKey("GovServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GovService");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceGeneralDocs", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.GovService", "GovService")
                        .WithMany("ServiceGeneralDocs")
                        .HasForeignKey("GovServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GovService");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceImportantNote", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.GovService", "GovService")
                        .WithMany("ImportantNotes")
                        .HasForeignKey("GovServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GovService");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceOption", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.GovService", "GovService")
                        .WithMany("ServiceOptions")
                        .HasForeignKey("GovServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GovService");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceOptionChoices", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.ServiceOption", "ServiceOption")
                        .WithMany("ServiceOptionChoices")
                        .HasForeignKey("ServiceOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOption");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceSteps", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.GovService", "GovService")
                        .WithMany("ServiceSteps")
                        .HasForeignKey("GovServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GovService");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.UserDocument", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.ChatSession", "ChatSession")
                        .WithMany("UserDocuments")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Khedmetak.DAL.Entities.RequiredDocument", "RequiredDocument")
                        .WithMany("UserDocuments")
                        .HasForeignKey("RequiredDocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Khedmetak.DAL.Entities.User", "User")
                        .WithMany("UserDocuments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChatSession");

                    b.Navigation("RequiredDocument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Khedmetak.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Khedmetak.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.Category", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("GovServices");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ChatSession", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Feedback");

                    b.Navigation("UserDocuments");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.GovService", b =>
                {
                    b.Navigation("ImportantNotes");

                    b.Navigation("RequiredDocuments");

                    b.Navigation("ServiceFeeTiers");

                    b.Navigation("ServiceGeneralDocs");

                    b.Navigation("ServiceOptions");

                    b.Navigation("ServiceSteps");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.RequiredDocument", b =>
                {
                    b.Navigation("UserDocuments");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.ServiceOption", b =>
                {
                    b.Navigation("ServiceOptionChoices");
                });

            modelBuilder.Entity("Khedmetak.DAL.Entities.User", b =>
                {
                    b.Navigation("ChatSessions");

                    b.Navigation("CitizenProfile");

                    b.Navigation("Feedbacks");

                    b.Navigation("Payments");

                    b.Navigation("UserDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
